FROM node:23-alpine3.20

RUN mkdir /app
WORKDIR /app

# install dependencies
COPY package.json package-lock.json* ./
RUN npm install

# copy source code
COPY . .

# run the app in developer mode with hot reload
ENTRYPOINT ["sh", "-c", "PORT=80 npm start"]